alert_config:
  - name: Neteng BB Input Errors Test
    config:
      scope: phy_interface
      source: grafana
      tags: [ neteng, bb, test ]
      severity: INFO
      auto_expire: true
      expire_after: 15m
      outputs: [ slack ]
      escalation_rules:
        - after: 5m
          escalate_to: WARN
        - after: 10m
          escalate_to: CRITICAL
          send_to: [ victorops ]
      # for: 15m # alert only if it keeps firing for 15 min

  - name: Neteng Device Unreachable
    config:
      scope: device
      source: observium 
      tags: [ neteng, bb, test ]
      severity: WARN
      outputs: [ slack ]
      escalation_rules:
        - after: 10m
          escalate_to: CRITICAL
          send_to: [ victorops ]

  - name: Neteng BB Util Out
    config:
      scope: phy_interface
      source: kapacitor
      severity: WARN
      tags: [ neteng, bb, util ]
      auto_expire: true # false by default
      expire_after: 2h
      outputs: [ slack ]
  
  - name: Neteng Transit Util Out
    config:
      scope: phy_interface
      source: grafana
      tags: [ neteng, pt, util ]
      severity: CRITICAL
      auto_clear: false # true by default
      outputs: [ slack, email]
      escalation_rules:
        - after: 15m
          escalate_to: CRITICAL
  
  - name: Neteng BB Link Down
    config:
      scope: link
      source: observium
      tags: [ neteng, bb, linkdown ]
      severity: INFO
      aggregation_rules:
        - fibercut

  - name: Neteng DC Link Down
    config:
      scopt: link
      source: observium
      tags: [ neteng, dc, linkdown ]
      severity: INFO
      aggregation_rules:
        - dc_circuit_down

  - name: Neteng BGP Down
    config:
      scope: bgp_peer
      source: observium
      tags: [ neteng, bgpdown ]
      severity: INFO
      aggregation_rules:
        - dc_circuit_down
        - bgp_session

aggregation_rules:
  - name: fibercut
    window: 5m
    alert:
      name: Neteng_Aggregated FiberCut
      config:
        source: aggregated
        severity: WARN
        tags: [ neteng, bb, fibercut ]
        outputs: [ slack ]
        escalation_rules:
          - after: 15m
            escalate_to: CRITICAL
            send_to: [ victorops ] 

  - name: bgp_session
    window: 1m
    alert:
      name: Neteng_Aggregated BGP Down
      config:
        source: aggregated
        severity: WARN
        tags: [ neteng, bgp ]
        auto_expire: true  ## aggregated alert will expire only when all component alerts expire
        outputs: [ slack ]
